services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/data
    networks:
      - kube-workshop

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - kube-workshop

volumes:
  backend-data:

networks:
  kube-workshop:
    name: kube-workshop
